### ISSUE TITLE
saran untuk menambahkan req.query

### ISSUE THREAD

**Issue by arsandev** [skuyjs/http-server#1]
saya punya saran untuk menambahkan req.query untuk return parameter get seperti di express js.

ketika saya coba masuk ke url localhost:8081/?test=123 hasilnya 404. sepertinya ada kesalahan di regex url.

**Comment by hadihammurabi** [comment]
Benar. Saat ini proses pembuatan route secara internal belum dapat mengenali query string.

Segera kami improve.

Terima kasih banyak atas feedback-nya, sungguh luar biasa.

**Comment by arsandev** [comment]
Saya sempat coba berkontribusi untuk fitur itu. tapi sepertinya agak sulit mengenali fungsi tiap line code. saya rasa _comment line_ penting untuk project open source.

tetap semangat!!

**Comment by hadihammurabi** [comment]
Thankyou atas semua masukannya. Pasti kami lakukan perbaikan dan berusaha menerapkan masukan-masukan positif.

**Comment by hadihammurabi** [comment]
Sudah fix di 47debb6d7eb1f3ee8559759763b9ea4b828dd793
Tapi masih memicu error, gak bisa nambah route lain karena semua route jadi match.
Ini problem di-regex-nya memang.

ASAP, dibenerin lagi.

**Comment by hadihammurabi** [comment]
Realy Realy Fixed at 19854ef398dfcb12841c04e7181efde2e7f3c87f
